import { adminState } from "./module/admin/type";
import { userState } from "./module/user/type";
import { PublicState } from "./module/public/type";
import { TypeStates } from "./module/type/type";
import { IntervewState } from "./module/interview/type";
import { issueState } from "./module/issue/type";
import { commentState } from "./module/comment/type";
import { ArticleState } from "./module/article/type";
type adminReducer = { adminInfo: adminState };
type userReducer = { userInfo: userState };
type publicReducer = { publicInfo: PublicState };
type typeReducer = { typeInfo: TypeStates };
type interviewReducer = { interviewInfo: IntervewState };
type issueReducer = { issue: issueState };
type commentReducer = { comment: commentState };
type ArticleReducer = { article: ArticleState };
export type rootReducer = {
  admin: adminReducer["adminInfo"];
  user: userReducer["userInfo"];
  public: publicReducer["publicInfo"];
  type: typeReducer["typeInfo"];
  interview: interviewReducer["interviewInfo"];
  issue: issueReducer["issue"];
  comment: commentReducer["comment"];
  article: ArticleReducer["article"];
};
